apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  ports:
  - name: http
    port: {{ .Values.servicePort }}
    protocol: TCP
    targetPort: {{ .Values.podPort }}
  selector:
    app: {{ .Values.name }}
  type: ClusterIP